name: StaffModeGUI2
version: ${project.version}
main: net.noodles.staffmodegui2.staffmodegui2.StaffModeGUI2
authors: [BGHDDevelopment, Noodles]
description: A StaffModeGUI Plugin
website: bghddevelopment.com
commands:
  staffmodedev:
    description: StaffModeDev command
    aliases: [smdev]
  staffmode:
    description: StaffMode command
    aliases: [sm, smgui]
  staffmodereload:
    description: StaffModeReload command
    aliases: [smreload]
softdepend:
  - PlaceholderAPI