name: StaffModeGUI2
version: ${project.version}
main: net.noodles.staffmodegui2.staffmodegui2.StaffModeGUI2
authors: [BGHDDevelopment, Noodles]
description: A StaffModeGUI Plugin
website: stephanbaumharvey.com
commands:
  staffmodedev:
  staffmode:
    aliases: [sm, smgui]

